baseURL = "https://davidhalewood.com/"
languageCode = "en-us"
title = "David Halewood"
theme = "hyde"

enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true

[author]
  name = "David Halewood"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  description = "Software Crafter working in London, UK"
  themeColor = "theme-base-azure"
  homeSubtitle = "A place for my thoughts and musings on all things software."

[menu]

  [[menu.main]]
    name = "Github"
    url = "https://www.github.com/haletothewood"
    weight = 20

  [[menu.main]]
    name = "Medium"
    url = "https://medium.com/@davidhalewood"
    weight = 20

  [[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/crafter_coder"
    weight = 20