baseURL = "https://davidhalewood.com/"
languageCode = "en-us"
title = "David Halewood"
theme = "gruvbox"

enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true

[permalinks]
 posts = "/:slug"

[params]
  author = { name = "David Halewood" }
  description = "Software Engineer (Craftsman) working remotely, UK and elsewhere"
  keywords = ["software engineering", "software craftsmanship", "blog", "programmer", "developer", "haletothewood"]
  titlePrefix = ""
  titleSuffix = " | davidhalewood.com"
  menuItemPrefix = "~/"
  postTruncateLength = 250
  hideGopher = true
  disqusAutoLoad = false
  disqusAutoLoadCount = false
  dateFormat = "2006-01-02"
  logo = "logo.jpg"

[[menu.links]]
  identifier = "posts"
  url = "/posts"

[[menu.social]]
  name = "Github"
  url = "https://www.github.com/haletothewood"
  weight = 1

[[menu.social]]
  name = "LinkedIn"
  url = "https://uk.linkedin.com/in/david-halewood-uk"
  weight = 100
